
services:
  nanosaur_simulator:
    image: nanosaur/simulation
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USER=${USER}
      - HOST_USER_UID=${USER_UID}
      - HOST_USER_GID=${USER_GID}
      - SIMULATOR_PACKAGE=${SIMULATION}
    network_mode: host
    ipc: host
    volumes:
      - /etc/localtime:/etc/localtime:ro